### ISSUE TITLE
Reflect supervised features relationship in the inspector's UI

### ISSUE THREAD

**Issue by MiSikora** [MiSikora/laboratory#95]
- [x] Indicate that a feature has a supervisor. (#119)
- [x] Navigate to supervisor from child. This can be tricky because features can be in different tabs. (b75e380)
- [x] Indicate what is supervised by an option. (#124)
- [x] Navigate to child from supervisor. Same issues as above. (#124)

**Comment by AlexKrupa** [comment]
How about minimal approach for a start, e.g. supervisor feature's name in a `TextView`?

```
------------------------------
ChristmasTheme
  Determines if Christmas theme is enabled.
  Enabled    Disabled
------------------------------
Greeting
  Supervisor: ChristmasTheme
  Determines greeting type if Christmas theme is enabled.
  Hello    HoHoHo
------------------------------
```

**Comment by MiSikora** [comment]
Sure, sounds good for a start. Want to make a PR?
